---
- name: Instalar y configurar MySQL en Ubuntu
  hosts: all  # Reemplaza 'all' con tu grupo de hosts
  become: yes

  tasks:
    - name: Actualizar la lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar el servidor MySQL
      apt:
        name: mysql-server
        state: present

    - name: Configurar el archivo de configuración de MySQL
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysql.cnf
        regexp: '^bind-address\s*='
        line: 'bind-address = 0.0.0.0'

    - name: Reiniciar el servicio de MySQL
      service:
        name: mysql
        state: restarted

    - name: Establecer la contraseña root de MySQL
      mysql_user:
        name: root
        password: tu_contraseña_segura
        host: '%'
        priv: ALL PRIVILEGES

    - name: Crear una base de datos (opcional)
      mysql_db:
        name: mi_base_de_datos
        owner: tu_usuario
