---
- name: Instalar MySQL en Ubuntu Server
  hosts: 192.168.171.162
  become: yes

  tasks:
    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar MySQL
      apt:
        name: mysql-server
        state: present

    - name: Configurar MySQL
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysql.cnf
        regexp: '^bind-address\s*='
        line: 'bind-address = 0.0.0.0'

    - name: Reiniciar servicio MySQL
      service:
        name: mysql
        state: restarted
