---
- name: Instalar MySQL en Ubuntu Server
  hosts: 192.168.171.162
  become: yes

  tasks:
    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar MySQL
      apt:
        name: mysql-server
        state: present

    - name: Reiniciar servicio MySQL
      service:
        name: mysql
        state: restart
