---
- name: Instalar Docker en un servidor Ubuntu
  hosts: all  # Define el grupo de hosts o el host donde se ejecutará el playbook
  become: true  # Se requiere sudo para instalar paquetes
  tasks:
    - name: Actualizar el caché de APT
      apt:
        update_cache: yes

    - name: Instalar paquetes necesarios para usar el repositorio de Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Añadir la clave GPG oficial de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Añadir el repositorio de Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Actualizar el caché de APT después de añadir el repositorio de Docker
      apt:
        update_cache: yes

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: latest

    - name: Iniciar y habilitar el servicio Docker
      service:
        name: docker
        state: started
        enabled: true

  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
